# Generated by Django 3.0.1 on 2023-04-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='personal_url')),
                ('content', models.TextField(blank=True)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
